export const APP_ID = "2fcb3aafd3a2b0258d94ef74fc758508";
export const CHANGE_CITY = "CHANGE_CITY";
export const DATA_FETCH_FULFILLED = "DATA_FETCH_FULFILLED";
export const DATA_FETCH_REJECTED = "DATA_FETCH_REJECTED";
export const AUTOCOMPLETE_DATA = "AUTOCOMPLETE_DATA";
export const SET_LOADING = "SET_LOADING";
